[package]
name = "egui-video"
version = "0.1.0"
edition = "2021"
exclude = [ "rust=ffmpeg" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.20.0"
ffmpeg-next = { git = "https://github.com/n00kii/rust-ffmpeg.git" }
anyhow = "1.0.66"
image = "0.24.4"
timer = "0.2.0"
chrono = "0.4.22"
tempfile = "3.3.0"

[dev-dependencies]
eframe = "0.20.0"